### ISSUE TITLE
Execution failed for task':checkDebugDuplicateClasses

### ISSUE THREAD

**Issue by outrageousactivity9** [MrZak-dev/GodotFAN#5]
![1](https://user-images.githubusercontent.com/63996014/79885370-68c25500-8414-11ea-8eff-f27755b33fcd.png)
![2](https://user-images.githubusercontent.com/63996014/79885396-7972cb00-8414-11ea-8e5b-b45cf7d48f56.png)
![3](https://user-images.githubusercontent.com/63996014/79885533-af17b400-8414-11ea-96e5-002b80047a8e.png)

I tried exporting to android but it is showing the above error. Can u please help me solve this error ?

**Comment by MrZak-dev** [comment]
Have you successfully exported your project to android without using the module ?

**Comment by outrageousactivity9** [comment]
> Have you successfully exported your project to android without using the module ?

Yes. The projects are exporting to android without this module

**Comment by MrZak-dev** [comment]
you can check i have pushed a new commit

**Comment by outrageousactivity9** [comment]
> you can check i have pushed a new commit

I checked your new commit; But now also i am getting that same error during export.
In the output console it is showing
![Presentation1](https://user-images.githubusercontent.com/63996014/80069428-f611c080-855e-11ea-975b-fc96a6c0d8c8.png)

**Comment by MrZak-dev** [comment]
![Success](https://user-images.githubusercontent.com/27586088/80154649-b384ce00-85c8-11ea-94a8-22f4fac0aa9d.png)

I was able to export an apk using the module without any errors .
i used Godot 3.2.2beta1 mono

**Comment by MrZak-dev** [comment]
![Annotation 2020-04-24 012656](https://user-images.githubusercontent.com/27586088/80155671-dca65e00-85ca-11ea-80d4-bc982e15f4ba.png)

**Comment by outrageousactivity9** [comment]
I changed the Godot version from 3.2.1-stable to Godot 3.2.2beta1 mono.
Now the module is exporting successfully. I am not getting any errors.
Is it due to change in gradle version; as 3.2.1 used gradle 5.1.1 but 3.2.2 used gradle 5.6.4 ?

**Comment by outrageousactivity9** [comment]
Thank u very mush for your assistance.
