### ISSUE TITLE
I can't install it

### ISSUE THREAD

**Issue by Kapsulon** [MrZak-dev/GodotFAN#7]
When i install it i get an error message because it can't get the singleton GodotFAN, i never created a singleton in the first place, do i need to put the java file in the plugins of the android compiler ?
![image](https://user-images.githubusercontent.com/59650514/97241177-97205300-17f0-11eb-8b76-8f9cf3e46037.png)

**Comment by phaitonican** [comment]
no, will need to install android template from godot menu and then put it into ur projects android folder. godot 3.2 doesn't need to recompile for android plugins/or handles it self idk exactly

**Comment by MrZak-dev** [comment]
Test on the example first .

**Comment by MrZak-dev** [comment]
place the GodotFAN folder inside `your_game_path/android`
