### ISSUE TITLE
Caching on Android 9

### ISSUE THREAD

**Issue by phaitonican** [MrZak-dev/GodotFAN#8]
Hello. FAN needs some caching changes on Android 9. (Having raise of errors on Android 9 since I implemented this plugin)

https://developers.facebook.com/docs/audience-network/android-network-security-config/

Now I try to edit the android manifest in android folder, but I don't see a way to include the file/application.

Any idea? Thanks for the plugin!

**Comment by MrZak-dev** [comment]
Testing ..

**Comment by MrZak-dev** [comment]
Please can you share the error log raised in Android 9 ?
are you sure it is caused by the plugin ?

**Comment by phaitonican** [comment]
i cant reproduce this anymore still thanks
