### ISSUE TITLE
Unable to get it to work (Engine.get_singleton("GodotFAN") is causing problems)

### ISSUE THREAD

**Issue by ai-boson** [MrZak-dev/GodotFAN#9]
Engine.get_singleton("GodotFAN") is returning null. So folder "GodotFAN" is not being fetched. I placed GodotFAN under android folder as mentioned and then  added modules="org/godotengine/godot/GodotFAN" in project setting > Compression> Android. 
What am I doing wrong as error is mostly on my side? Thanks for your time.
Code is like this only for interstitial ads:
```
var facebookAds
func ready()
         facebookAds = Engine.get_singleton("GodotFAN")
	facebookAds.FacebookAdsInit(get_instance_id(),"758484777344_6483885593","","")
```

**Comment by MrZak-dev** [comment]
did you tried using the Example provided with the plugin ?

**Comment by ai-boson** [comment]
Sorry for the late reply as the email went in spam. Yes, I tried it with
the example provided and it gives an error: Couldn't find singleton for
class: org/godotengine/godot/GodotFAN (logcat attached below). So I placed
the GodotFAN/src/GodotFAN.java inside the android folder. And then the
execution of the build failed (image attached below).
Thanks for your time.

**Comment by MrZak-dev** [comment]
You should place the complete folder iside of android folder : ex : `my_game_path/android/GodotFAN`

**Comment by MrZak-dev** [comment]
https://user-images.githubusercontent.com/27586088/103157266-36969d80-47c2-11eb-9087-d013a196c099.mp4

I have tested the plugin on the last stable version of godot `3.2.3`, it is still working as expected

**Comment by ai-boson** [comment]
Can you check the attached screenshot below and tell me whether the folder
placement is correct? Also in the screenshot on the right side (last line)
it says failed to retrieve non-existent singleton "GodotFAN".

**Comment by MrZak-dev** [comment]
The folder architecture should be the same as the example provided with the plugin , check it .

**Comment by ai-boson** [comment]
I tried everything. But Engine.get_singleton("GodotFAN") returns null
always. Is there a way I can just add some java test file so that it
returns not null just to check? Also I am using windows. Can that be the
reason that it is not working?

**Comment by MrZak-dev** [comment]
are you testing on Android or only on windows ?

**Comment by ai-boson** [comment]
Checked on phone. Bug report on phone is attached.

**Comment by ai-boson** [comment]
issue in bug report is similar as this
https://github.com/godotengine/godot/issues/22859

**Comment by ai-boson** [comment]
error: cannot find symbol interstitialAd.setALlistener(new
InterstitialAdListener()
Any idea why is it occurring on line 69 of GodotFAN.java? Please check the
screenshot. There are 3 errors like this.
